import = [
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/my-theme.toml"
]

# "window.dynamic_title" = true

[shell]
# program = "/usr/bin/zsh"
program = "/usr/bin/fish"
# program = "/usr/bin/bash"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 10

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[font.bold]
# family = "MesloLGSDZ Nerd Font"
style = "bold"
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"
# family = "MesloLGSDZ Nerd Font"
style = "italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "MesloLGSDZ Nerd Font"
style = "regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
opacity =  0.80
dynamic_padding = true

[window.dimensions]
columns = 110
lines = 26

[window.padding]
x = 5
y = 5

[env]
term = "alacritty"


